### ISSUE TITLE
PyPi

### ISSUE THREAD

**Issue by mesca** [pyRiemann/pyRiemann#121]
Any hope for a new PyPi package soon? 
The current version is broken and we need to add PyRiemann as a dependency to several PIP packages. Unfortunately, because of [this issue](https://github.com/pypa/warehouse/issues/7136), we cannot directly link to the git repository.
Currently, we prompt users to install PyRiemann separately, but this is far from ideal.

**Comment by lkorczowski** [comment]
FYI I had to use `pip install --upgrade --force-reinstall git+https://github.com/pyRiemann/pyRiemann` because I inadvertently did `pip install pyriemann`. I think the version in setup  needs to be updated
https://github.com/pyRiemann/pyRiemann/blob/acd7d34f4f8d97ebe7e7d0f164332d56511e54c4/setup.py#L4

**Comment by qbarthelemy** [comment]
Yep, it should be '0.2.7.dev'.

**Comment by agramfort** [comment]
shall we release after the Whitening PR?

>

**Comment by mesca** [comment]
> shall we release after the Whitening PR?

I guess so.

**Comment by sylvchev** [comment]
We could release the 0.27 !

**Comment by agramfort** [comment]
0.2.7 has been on pypi for a few days now

https://pypi.org/project/pyriemann/

>
